using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using System.Xml.Serialization;
using System.Xml;
//using Glider;
//using Glider.Common;
//using Glider.DataPool.Data;
namespace MyUITest
{
    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.3038.
    // 
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute("param", Namespace = "", IsNullable = false)]
    public partial class Param
    {
        private string nameField;
        private string valueField;
        private string paramValue;
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type { get; set; }
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        [System.Xml.Serialization.XmlTextAttribute()]
        public string ParamValue
        {
            get
            {
                return this.paramValue;
            }
            set
            {
                this.paramValue = value;
            }
        }
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute("Action",Namespace = "", IsNullable = false)]
    public partial class Action
    {
        public Action()
        {
            this.paramField = new List<Param>();
            this.ExtendedProperties = new List<ExtendedProperty>();
        }
        private List<Param> paramField;
        private string nameField;
        private string componentNameField;
        private string controlNameField;
        private string valueField;
        private string returnRef;
        private string searchProperties;
        [System.Xml.Serialization.XmlElementAttribute("param")]
        public List<Param> param
        {
            get
            {
                return this.paramField;
            }
            set
            {
                this.paramField = value;
            }
        }
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentName
        {
            get
            {
                return this.componentNameField;
            }
            set
            {
                this.componentNameField = value;
            }
        }
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ControlName
        {
            get
            {
                return this.controlNameField;
            }
            set
            {
                this.controlNameField = value;
            }
        }
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReturnRef
        {
            get
            {
                return this.returnRef;
            }
            set
            {
                this.returnRef = value;
            }
        }
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SearchProperties
        {
            get
            {
                return searchProperties;
            }
            set
            {
                searchProperties = value;
            }
        }
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OverrideProperty { get; set; }
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OverrideValue { get; set; }
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransactionName { get; set; }
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransactionStep { get; set; }

        [XmlArray("ExtendedProperties")]
        [XmlArrayItem("ExtendedProperty")]
        public List<ExtendedProperty> ExtendedProperties { get; set; }
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute("testCase", Namespace = "", IsNullable = false)]
    public partial class TestCase
    {
        public TestCase()
        {
            this.actionsListField = new List<Actions>();
        }
        private List<Actions> actionsListField;
        private string idField;
        private string titleField;
        private string testCasePath;
        private string testPsPath;
        [System.Xml.Serialization.XmlElementAttribute("actions", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<Actions> actionsList
        {
            get
            {
                return this.actionsListField;
            }
            set
            {
                this.actionsListField = value;
            }
        }
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PSPath
        {
            get
            {
                return this.testPsPath;
            }
            set
            {
                this.testPsPath = value;
            }
        }
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StorePath
        {
            get
            {
                return this.testCasePath;
            }
            set
            {
                this.testCasePath = value;
            }
        }
        public static TestCase CreateInstanceFromXML(string testXml)
        {
            XmlSerializer serializer = new XmlSerializer(typeof(TestCase));
            //testXml = DataPoolStore.DefaultStore.MergeTestData(testXml);
            using (var sr = new StringReader(testXml))
            {
                return (TestCase)serializer.Deserialize(sr);
            }
        }
        public static void SerializeInstanceToXML(TestCase testCase)
        {
            XmlSerializer serializer = new XmlSerializer(typeof(TestCase));
            using (var fs = new FileStream("..\\..\\Test\\testcase1.xml", FileMode.Create))
            {
                serializer.Serialize(fs, testCase);
                fs.Close();
            }
        }
        public static TestCase CreateInstanceFromXMLFile(string fileName)
        {
            XmlSerializer serializer = new XmlSerializer(typeof(TestCase));
            using (StreamReader sr = new StreamReader("..\\..\\Test\\testcase1.xml"))
            {
                using (var r = new StringReader(sr.ReadToEnd()))
                {
                    return (TestCase)serializer.Deserialize(r);
                }
            }
        }
    }
    
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class Actions
    {
        public Actions()
        {
            this.actionField = new List<Action>();
        }
        private List<Action> actionField;
        private string descriptionField;

        [System.Xml.Serialization.XmlElementAttribute("action")]
        public List<Action> actions
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
}
//namespace MyUITest
//{
//    public class TestCase
//    {
//        string action;
//        string param;
//    }
//}