//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using System.IO;
using System.Xml.Serialization;
using Glider;
using Glider.Common;
using Glider.DataPool.Data;

namespace Glider
{
    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.3038.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute("param", Namespace = "", IsNullable = false)]
    public partial class Param
    {

        private string nameField;

        private string valueField;

        private string paramValue;

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type { get; set; }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
        [System.Xml.Serialization.XmlTextAttribute()]
        public string ParamValue
        {
            get
            {
                return this.paramValue;
            }
            set
            {
                this.paramValue = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Action
    {


        public Action()
        {
            this.paramField = new List<Param>();

            this.ExtendedProperties = new List<ExtendedProperty>();

        }

        private List<Param> paramField;

        private string nameField;

        private string componentNameField;

        private string controlNameField;

        private string valueField;

        private string returnRef;

        private string searchProperties;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("param")]
        public List<Param> param
        {
            get
            {
                return this.paramField;
            }
            set
            {
                this.paramField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ComponentName
        {
            get
            {
                return this.componentNameField;
            }
            set
            {
                this.componentNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ControlName
        {
            get
            {
                return this.controlNameField;
            }
            set
            {
                this.controlNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ReturnRef
        {
            get
            {
                return this.returnRef;
            }
            set
            {
                this.returnRef = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SearchProperties
        {
            get
            {
                return searchProperties;
            }
            set
            {
                searchProperties = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OverrideProperty { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OverrideValue { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransactionName { get; set; }

        //[System.Xml.Serialization.XmlAttributeAttribute()]
        //public string TransactionScenario { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransactionStep { get; set; }

        /// <summary>
        /// 
        /// </summary>
        [XmlArray("ExtendedProperties")]
        [XmlArrayItem("ExtendedProperty")]
        public List<ExtendedProperty> ExtendedProperties { get; set; }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute("testCase", Namespace = "", IsNullable = false)]
    public partial class TestCase
    {


        public TestCase()
        {
            this.actionsField = new List<Actions>();
        }

        private List<Actions> actionsField;

        private string idField;

        private string titleField;        

        private string testCasePath;

        private string testPsPath;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("actions", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public List<Actions> actionsList
        {
            get
            {
                return this.actionsField;
            }
            set
            {
                this.actionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        //[Obsolete("Use StorePath instead of PSPath")]
        public string PSPath
        {
            get
            {
                return this.testPsPath;
            }
            set
            {
                this.testPsPath = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string StorePath
        {
            get
            {
                return this.testCasePath;
            }
            set
            {
                this.testCasePath = value;
            }
        }

        /// <summary>
        /// Create TestCase object from XML
        /// </summary>
        /// <param name="testXml"></param>
        /// <returns></returns>
        /// <remarks>Added By: A M Belton on 4th Sept 2012</remarks>
        public static TestCase CreateInstanceFromXML(string testXml)
        {
            XmlSerializer serializer = new XmlSerializer(typeof(TestCase));                                          
                 
            testXml = DataPoolStore.DefaultStore.MergeTestData(testXml);
            using (var sr = new StringReader(testXml))
            {
                return (TestCase)serializer.Deserialize(sr);
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class Actions
    {

        public Actions()
        {
            this.actionField = new List<Action>();
        }

        private List<Action> actionField;

        private string descriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("action")]
        public List<Action> action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

}